doc/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'doc'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^checker/$', views.checker, name='checker'),
    url(r'^login', auth_views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^accounts/login/', auth_views.login, name='acc_login'),
    url(r'^logout', auth_views.logout, name='logout'),
    url(r'^patient_register/$', views.p_signup, name='p_signup'),
    url(r'^doctor_register/$', views.d_signup, name='d_signup'),
    url(r'^blog/$', views.BlogView.as_view(), name='blog'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # url(r'^profile/$', views.update_profile, name='profile'),
    url(r'^symptoms/$', views.SymptomView.as_view(), name='symptoms'),
    url(r'^patients/$', views.PatientsView.as_view(), name='patients'),
    url(r'^patients/(?P<pk>[0-9]+)/$', views.PatientDetailView.as_view(), name='patient_detail'),
    url(r'^diseases/$', views.DiseaseView.as_view(), name='diseases'),
    url(r'^diseases/(?P<pk>[0-9]+)/$', views.DisDetailView.as_view(), name='dis_detail'),
    url(r'^blog/(?P<pk>[0-9]+)/$', views.BlogDetailView.as_view(), name='blogpost'),
    url(r'^typeofdoc/(?P<pk>[0-9]+)/$', views.TodDetailView.as_view(), name='tod_detail'),
    url(r'^typeofdoc/$', views.TodView.as_view(), name='tod'),

]

webdoc/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('doc.urls')),
]

doc/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class TypeofDoc(models.Model):
    category = models.CharField(max_length=50)
    detail = models.CharField(max_length=1200)

    def __str__(self):
        return self.category


class Symptoms(models.Model):
    s_name = models.CharField(max_length=100)

    def __str__(self):
        return self.s_name


class Disease(models.Model):
    dis_name = models.CharField(max_length=30)
    dis_type = models.CharField(max_length=20, default="Null")
    dis_detail = models.CharField(max_length=2000)
    medicine = models.CharField(max_length=300, default="Not Available")

    def __str__(self):
        return self.dis_name


class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='p_profile')
    p_name = models.CharField(max_length=30)
    p_gender = models.CharField(max_length=20)
    p_address = models.CharField(max_length=200)
    p_email = models.CharField(max_length=50)
    p_dob = models.DateField(null=True)
    p_blood_grp = models.CharField(max_length=10)
    p_contact = models.CharField(max_length=20)

    def __str__(self):
        return self.p_name


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='d_profile')
    d_name = models.CharField(max_length=30)
    d_gender = models.CharField(max_length=20)
    d_email = models.CharField(max_length=50)
    clinic_add = models.CharField(max_length=200)
    d_dob = models.DateField(null=True)
    visit_hours = models.CharField(max_length=20)
    d_detail = models.CharField(max_length=1200)
    specialization = models.CharField(max_length=30)
    d_contact = models.CharField(max_length=20)

    def __str__(self):
        return self.d_name

class Blog(models.Model):
    did = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=10000)
    time = models.DateTimeField()

    def __str__(self):
        return self.title


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Doctor.objects.create(user=instance)
        Patient.objects.create(user=instance)
    instance.d_profile.save()
    instance.p_profile.save()


'''    class Meta:
        verbose_name = 'p_profile'
        verbose_name_plural = 'profiles'
'''


class PatientRecord(models.Model):
    pid = models.ForeignKey(Patient, on_delete=models.CASCADE)
    mother_name = models.CharField(max_length=30)
    father_name = models.CharField(max_length=30)
    medical_history = models.CharField(max_length=2000)
    physically_challenged = models.BooleanField(default=False)
    mentally_challenged = models.BooleanField(default=False)


class Relation(models.Model):
    sid = models.ForeignKey(Symptoms, on_delete=models.CASCADE)
    did = models.ForeignKey(Disease, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.did)

doc/forms.py
from django import forms
from django.forms import extras
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Symptoms


class CheckerForm(forms.Form):
    Symptom1 = forms.ModelChoiceField(queryset=Symptoms.objects.all().order_by('s_name'))
    Symptom2 = forms.ModelChoiceField(queryset=Symptoms.objects.all().order_by('s_name'))
    Symptom3 = forms.ModelChoiceField(queryset=Symptoms.objects.all().order_by('s_name'))


DOY = ('1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
       '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003',
       '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016')


class PSignUpForm(UserCreationForm):
    p_name = forms.CharField()
    p_gender = forms.CharField()
    p_address = forms.CharField()
    p_email = forms.EmailField()
    p_dob = forms.DateField(widget=extras.SelectDateWidget(years=DOY,
        empty_label=("Choose Year", "Choose Month", "Choose Day"),),)
    p_blood_grp = forms.CharField()
    p_contact = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'p_name', 'p_gender', 'p_address', 'p_email', 'p_dob', 'p_blood_grp', 'p_contact', 'password1', 'password2', )


class DSignUpForm(UserCreationForm):
    d_name = forms.CharField()
    d_gender = forms.CharField()
    clinic_add = forms.CharField()
    d_email = forms.EmailField()
    d_dob = forms.DateField(widget=extras.SelectDateWidget(years=DOY, empty_label="Nothing"))
    visit_hours = forms.CharField()
    d_detail = forms.CharField()
    specialization = forms.CharField()
    d_contact = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'd_name', 'd_gender', 'clinic_add', 'd_email', 'd_dob', 'visit_hours', 'd_detail', 'specialization', 'd_contact', 'password1', 'password2', )

doc/views.py
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from .models import Symptoms, Disease, Blog, Patient, Relation, TypeofDoc
from django.contrib.auth import authenticate, login
from .forms import PSignUpForm, DSignUpForm, CheckerForm


@login_required
def dashboard(request):
    return render(request, 'doc/dashboard.html')


def register(request):
    return render(request, 'registration/register.html')


def p_signup(request):
    if request.method == 'POST':
        p_form = PSignUpForm(request.POST)
        if p_form.is_valid():
            user = p_form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.p_profile.p_dob = p_form.cleaned_data.get('p_dob')
            user.p_profile.p_name = p_form.cleaned_data.get('p_name')
            user.p_profile.p_gender = p_form.cleaned_data.get('p_gender')
            user.p_profile.p_address = p_form.cleaned_data.get('p_address')
            user.p_profile.p_blood_grp = p_form.cleaned_data.get('p_blood_grp')
            user.p_profile.p_contact = p_form.cleaned_data.get('p_contact')
            user.save()
            raw_password = p_form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/dashboard/')
    else:
        p_form = PSignUpForm()
    return render(request, 'registration/patient_register.html', {'p_form': p_form})


def d_signup(request):
    if request.method == 'POST':
        form = DSignUpForm(request.POST)
        if form.is_valid():
            d_user = form.save()
            d_user.refresh_from_db()  # load the profile instance created by the signal
            d_user.d_profile.d_dob = form.cleaned_data.get('d_dob')
            d_user.d_profile.d_name = form.cleaned_data.get('d_name')
            d_user.d_profile.d_gender = form.cleaned_data.get('d_gender')
            d_user.d_profile.clinic_add = form.cleaned_data.get('clinic_add')
            d_user.d_profile.visit_hours = form.cleaned_data.get('visit_hours')
            d_user.d_profile.d_contact = form.cleaned_data.get('d_contact')
            d_user.d_profile.d_detail = form.cleaned_data.get('d_detail')
            d_user.d_profile.specialization = form.cleaned_data.get('specialization')
            d_user.save()
            raw_password = form.cleaned_data.get('password1')
            d_user = authenticate(username=d_user.username, password=raw_password)
            login(request, d_user)
            return redirect('/dashboard/')
    else:
        form = DSignUpForm()
    return render(request, 'registration/doc_register.html', {'form': form})

"""
def checker(request, ):
    result = Relation.objects.get(sid=)
"""

def index(request):
    return render(request, 'doc/index.html')


def about(request):
    return render(request, 'doc/about.html')


def checker(request):

    if request.method == "POST":
        form = CheckerForm(request.POST)
        if form.is_valid:
            s1 = request.POST.get('Symptom1')
            s2 = request.POST.get('Symptom2')
            s3 = request.POST.get('Symptom3')
            diseases1 = Relation.objects.filter(sid=s1)
            diseases2 = Relation.objects.filter(sid=s2)
            diseases3 = Relation.objects.filter(sid=s3)
            diseases12 = diseases1.filter(
                did__in=diseases2.values_list('did', flat=True)
            )
            diseases = diseases12.filter(
                did__in=diseases3.values_list('did', flat=True)
            )
            return render(request, 'doc/checker.html', {
                'form': form,
                'diseases': diseases,
            })
        else:
            return HttpResponseRedirect('/')
    else:
        form = CheckerForm()
        return render(request, 'doc/checker.html', {
            'form': form,

        })
    return render(request, 'doc/checker.html', diseases)



'''def checker(request):

    return render(request, 'doc/checker.html', {
        'hello':'hello world',
        'form': CheckerForm()

    })'''


class BlogView(generic.ListView):
    template_name = 'doc/blog_list.html'
    context_object_name = 'all_blogs'

    def get_queryset(self):
        return Blog.objects.all()


class SymptomView(generic.ListView):
    template_name = 'doc/symptoms.html'
    context_object_name = 'all_symptoms'

    def get_queryset(self):
        return Symptoms.objects.all()


class PatientsView(generic.ListView):
    template_name = 'doc/patients.html'
    context_object_name = 'all_patients'

    def get_queryset(self):
        return Patient.objects.exclude(p_name__isnull=True).exclude(p_name__exact='')


class PatientDetailView(generic.DetailView):
    model = Patient
    template_name = 'doc/patient_detail.html'


class DiseaseView(generic.ListView):
    template_name = 'doc/diseases.html'
    context_object_name = 'all_diseases'

    def get_queryset(self):
        return Disease.objects.all()


class DisDetailView(generic.DetailView):
    model = Disease
    template_name = 'doc/dis_detail.html'


class BlogDetailView(generic.DetailView):
    model = Blog
    template_name = 'doc/blogpost.html'


class CheckerView(generic.ListView):
    template_name = 'doc/checker.html'
    context_object_name = 'all_symptoms'

    def get_queryset(self):
        return Symptoms.objects.all()


class TodView(generic.ListView):
    template_name = 'doc/tod.html'
    context_object_name = 'all_tod'

    def get_queryset(self):
        return TypeofDoc.objects.all()


class TodDetailView(generic.DetailView):
    model = TypeofDoc
    template_name = 'doc/tod_detail.html'

doc/templates/doc/about.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}About{% endblock %}
{% block content %}

    <header style="background-image: url('/static/img/portfolio/about.jpeg');">
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading" style="color:black;">About Us</h1>
                <br>
                <h3 class="section-heading" style="color:black;">Helping you Understand your symptoms better!</h3>
                <hr>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More About Us!</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">About Us</h2>
                    <hr class="light">
                    <h3 class="section-heading">The WebDoc Mission</h3>
                    <p class="text-faded">The WebDoc Symptom Checker
                         Our mission is to be your most trusted ally in your pursuit of health and well-being.
                    </p>
                    <hr class="light">
                    <h3 class="section-heading">The WebDoc Symptom Checker Overview</h3>
                    <p class="text-faded">

                        The WebDoc Symptom Checker is very different. For the first time, it gives you access to a highly sophisticated medical diagnosis tool that is much more powerful than previously available symptom checkers. Using the latest searching technologies, the system can take a pattern of symptoms in everyday language and instantly compute from our vast database of diseases, the most likely ones.
                        <br>
                        <br>
                        You can depend on us to provide expert content along with genuine caring. Both of which will support, guide, and inspire you toward the best possible health outcomes for you and your family.
                        <br>
                        <br>
                        The WebDoc Symptom Checker puts the world's medical knowledge at your fingertips and enables you to make sense of your symptoms. It will change the way you speak to your doctor forever!
                        <br>
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

doc/templates/doc/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>WebDoc+ | {% block title %}{% endblock %}</title>

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/creative.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
    input {
        color: black;
    }
    </style>

{% block style %}
{% endblock %}
</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>

                <a style="font-family: 'Kaushan Script', cursive;" class="navbar-brand page-scroll" href="/">WebDoc+</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="/symptoms/">Symptoms</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/about/">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/checker/">Check Your Symptoms</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/typeofdoc/">Doctors</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/blog/">Blog</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="/diseases/">Diseases</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="page-scroll" href="/dashboard">Dashboard</a>
                    </li>
                    {% else %}
                    <li>
                        <a class="page-scroll" href="/login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% block content %}{% endblock %}

    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Have any questions for us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x sr-contact"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:feedback@webdoc.com">feedback@webdoc.com</a></p>
                </div>
            </div>
        </div>
    </section>


    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/creative.min.js' %}"></script>


    <!--Start of Tawk.to Script-->
    <script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/591379a864f23d19a89b19b0/default';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
    })();
    </script>
    <!--End of Tawk.to Script-->

</body>

</html>

doc/templates/doc/blog_list.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block content %}

    <header style="background-image: url('/static/img/portfolio/blog.jpg');">
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Blog</h1>
                <hr>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Our Blogs!</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    {% if all_blogs  %}
                        <h2>Blogs:</h2>
                        <br>
                        <ul>
                            {% for blog in all_blogs %}
                            <li><a style="color: white; font-size:20px;" href="{% url 'doc:blogpost' blog.id %}">{{ blog.title }}</a></li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <h3>We don't have any blogs currently!</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

doc/templates/doc/blogpost.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Disease_Detail{% endblock %}
{% block content %}


    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h1>{{ blog.title }}</h1>
                    <br>
                    <p>{{ blog.content }}</p>
                    <br>
                    <p>Posted on - {{ blog.time }}</p>
                    <h3>- By {{ blog.did }}</h3>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

doc/templates/doc/checker.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Symptom Checker{% endblock %}
{% block content %}

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">

                    <h1>Symptom Checker </h1>
                    <h3>Select you symptoms</h3>
                    <br>
                    <form method="post">
                        {% csrf_token %}
                        {{form}}
                        <br>
                        <br>
                        <br>
                        <button type="submit" class="btn btn-info" value="Submit Button">Check for diseases</button>
                    </form>
                    <br>
                    <br>

                    {% if diseases %}
                    <h3>Diseases:</h3>
                    <br>
                    {% for disease in diseases %}
                        <p>{{ disease.did }}</p>
                    {% endfor %}
                    {% endif %}

                </div>
            </div>
        </div>
    </section>

{% endblock %}

doc/templates/doc/dis_detail.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Disease_Detail{% endblock %}
{% block content %}


    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h1>{{ disease.dis_name }}</h1><br>
                    <p>Type of disease: {{ disease.dis_type }}</p>
                    <p>{{ disease.dis_detail }}</p>
                    <p>Medicines: {{ disease.medicine }}</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

doc/templates/doc/diseases.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Diseases{% endblock %}
{% block content %}

    <header style="background-image: url('/static/img/portfolio/diseases.jpg');">
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Diseases A-Z</h1>
                <hr>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Click here for Diseases list</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    {% if all_diseases  %}
                        <h3>Here's a list of all Diseases:</h3><br>

                            {% for disease in all_diseases %}
                            <p><a style="color: black;" href="{% url 'doc:dis_detail' disease.id %}">{{ disease.dis_name }}</a></p>
                            {% endfor %}

                    {% else %}
                        <h3>There are no Diseases in our Database probably our data entry guys are too lazy!</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

doc/templates/doc/patient_detail.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Patient_Detail{% endblock %}
{% block content %}


    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p>Name: {{ patient.p_name }}</p>
                    <p>Gender: {{ patient.p_gender }}</p>
                    <p>Address: {{ patient.p_address }}</p>
                    <p>Your birth date: {{ patient.p_dob }}</p>
                    <p>Blood Group: {{ patient.p_blood_grp }}</p>
                    <p>Contact: {{ patient.p_contact }}</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

doc/templates/doc/patients.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Patients{% endblock %}
{% block content %}

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    {% if all_patients  %}
                        <h3>Here's a list of all patients:</h3>

                            {% for patient in all_patients %}
                            <p><a style="color: black;" href="{% url 'doc:patient_detail' patient.id %}">{{ patient.p_name }}</a></p>
                            {% endfor %}

                    {% else %}
                        <h3>There are no Patients in our System! Please try again later.</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

doc/templates/doc/profile.html
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>

doc/templates/doc/symptoms.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}Symptoms{% endblock %}
{% block content %}

    <header style="background-image: url('/static/img/portfolio/symptoms.jpg');">
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Symptoms</h1>
                <hr>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Click here for Symptoms list</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    {% if all_symptoms  %}
                        <h2>Symptoms A-Z</h2>
                        <br>
                        <h3>Here's a list of all Symptoms:</h3><br>
                            {% for symptom in all_symptoms %}
                            <p>{{ symptom.s_name }}</p>
                            {% endfor %}

                    {% else %}
                        <h3>There are no Symptoms in our Database probably our data entry guys are too lazy!</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

doc/templates/doc/tod.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}tod{% endblock %}
{% block content %}

    <header style="background-image: url('/static/img/todimage.jpg');">
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading" style="color:blue">Types of Doctors</h1>
                <hr>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Click here for Doctors' list</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    {% if all_tod %}
                        <h3>Here's a list of all types of Doctors:</h3><br>

                            {% for TypeofDoc in all_tod %}
                            <p><a style="color: black;" href="{% url 'doc:tod_detail' TypeofDoc.id %}">{{ TypeofDoc.category }}</a></p>
                            {% endfor %}

                    {% else %}
                        <h3>There are no Type of doctors in our Database probably our data entry guys are too lazy!</h3>
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

doc/templates/doc/tod_detail.html
{% extends 'doc/base.html' %}
{% load static %}
{% block title %}tod_detail{% endblock %}
{% block content %}


    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h1>{{ TypeofDoc.category }}</h1><br>
                    <p>{{ TypeofDoc.detail }}</p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}